layout_spectrum: 1
typography_spectrum: 0.5412186
color:
  saturation: 0.4623656
  brandStrength: 0.453405
  lightness: 0.4175627
  brandColors:
    - '#393939'
    - '#F9FAF9'
    - '#93989A'
    - '#FF706C'
    - '#C6396D'
  rhythmicContrast: 0.4605735
name: Sostartup
