name: Sostartup
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#11b4d7'
    - '#dc3c2e'
    - '#bd00b6'
    - '#07080d'
  brandStrength: 0.453405
  lightness: 0.4175627
  saturation: 0.4623656
  rhythmicContrast: 0.4605735
purpose: []
