layout_spectrum: 1
color:
  saturation: 0.7293907
  brandStrength: 0.453405
  lightness: 0.781362
  brandColors:
    - '#393939'
    - '#F9FAF9'
    - '#93989A'
    - '#FF706C'
    - '#C6396D'
  rhythmicContrast: 0.5089605
typography_spectrum: 0.5412186
name: Sostartup
