name: shaula
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#11b4d7'
    - '#dc3c2e'
    - '#bd00b6'
    - '#07080d'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
